---
- name: Provision Nginx
  hosts: task-12-web-server-tf
  become: true
  become_method: sudo
  tasks:
    - name: Install Nginx
      dnf:
        name: nginx
        state: latest

    - name: Enable and start Nginx
      service:
        name: nginx
        state: started
        enabled: true

    - name: Create index.html file for Nginx
      template:
        src: ./index-tf.html
        dest: /usr/share/nginx/html/index.html
        owner: root
        group: root
        mode: 0644